Release: Marge develop branch to main
Touqeerjadoon/Assignment-1 pull request #3
Opened 2024-12-30 04:24 UTC by Touqeerjadoon

Update docker-compose.yaml file.
Remove Dockerfile comments.
Fix bugs.

2024-12-30 06:42 UTC, Abdullahxz requested changes

2024-12-30 06:42 UTC, Abdullahxz commented on Dockerfile
> +CMD ["node", "server.js"]
Dockerfile is still lacking best practices. Please have a look here
https://docs.docker.com/build/building/best-practices/

2024-12-31 06:43 UTC, Abdullahxz requested changes

2024-12-31 06:43 UTC, Abdullahxz commented on Dockerfile
> +COPY ./app /home/app
I think you do not need to use `/home/app` with `WORKDIR` directive.

2024-12-31 06:43 UTC, Abdullahxz commented on Dockerfile
> +EXPOSE 3000
Is this needed?

2024-12-31 07:10 UTC, Touqeerjadoon commented on Dockerfile
> +EXPOSE 3000
It's a optional step but it helps other developers understand the port configuration. If not needed, i can remove it.

2024-12-31 07:33 UTC, Touqeerjadoon commented on Dockerfile
> +COPY ./app /home/app
yes, you are right it already set in work directory.

2024-12-31 09:57 UTC, Abdullahxz requested changes

2024-12-31 09:57 UTC, Abdullahxz commented on Dockerfile
> +COPY ./app /home/app
Please update this in the dockerfile.

2024-12-31 12:47 UTC, Touqeerjadoon commented on Dockerfile
> +COPY ./app /home/app
Updated, please review my Dockerfile again.

2024-12-31 12:49 UTC, Abdullahxz approved these changes
Nice one

2024-12-31 12:57 UTC, merged